# site.yml
---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    required_storage_gb: 500
    eth_rpc_url: "{{ lookup('env', 'ETH_RPC_URL') | default('') }}"

  tasks:

   - name: Include Starknet validator roles
     include_role: starknet-validator-automation