# tasks/container_deployment.yml
---
- name: Check if snapshots directory exists
  stat:
    path: "{{ selected_mount.mount }}/snapshots"
  register: snapshots_dir
  when: selected_mount is defined

- name: Fail if snapshots directory doesn't exist
  fail:
    msg: "Snapshots directory not found at {{ selected_mount.mount }}/snapshots. Please run snapshot download first."
  when: selected_mount is defined and not snapshots_dir.stat.exists

- name: Check if ETH_RPC_URL is provided
  fail:
    msg: "ETH_RPC_URL environment variable is required. Please set it with: export ETH_RPC_URL='your_wss_endpoint'"
  when: eth_rpc_url == ""

- name: Stop existing Juno container if running
  command: docker stop juno
  ignore_errors: yes

- name: Remove existing Juno container if exists
  command: docker rm juno
  ignore_errors: yes

- name: Run Juno Docker container
  command: >
    docker run -d --name juno
    -p 6060:6060 -p 6061:6061
    -v {{ selected_mount.mount }}/snapshots:/snapshots/juno
    nethermind/juno
    --network sepolia
    --http --http-port 6060 --http-host 0.0.0.0
    --ws --ws-port 6061 --ws-host 0.0.0.0
    --eth-node {{ eth_rpc_url }}
    --db-path /snapshots/juno
  register: juno_container
  when: selected_mount is defined

- name: Display Juno container status
  debug:
    msg: "Juno container started with ID: {{ juno_container.stdout }}"
  when: juno_container is defined and juno_container.rc == 0

- name: Wait for Juno to start
  wait_for:
    port: 6060
    host: localhost
    delay: 10
    timeout: 60

- name: Verify Juno is running
  uri:
    url: http://localhost:6060
    method: GET
    timeout: 10
  register: juno_health_check
  ignore_errors: true

- name: Display Juno status
  debug:
    msg: "Juno is {{ 'running and responding' if juno_health_check.status == 200 else 'not responding' }}"

- name: Show connection information
  debug:
    msg: |
      Juno node is running!
      HTTP endpoint: http://localhost:6060
      WebSocket endpoint: ws://localhost:6061
      Snapshots mounted from: {{ selected_mount.mount }}/snapshotsd