# starknet-validator-automation/tasks/main.yml
---
- name: "Phase 0: Detect and validate vars"
  include_tasks: 
    file: detect_vars.yml
    apply:
      tags: vars
  tags:
   - vars

# Mount Detection Phase
# Nice gotcha https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
- name: "Phase 1: Detect and validate storage mounts"
  include_tasks: 
    file: mount_detection.yml
    apply:
      tags: mount
  tags:
   - mount

# Snapshot Download Phase  
- name: "Phase 2: Download and extract Starknet snapshot"
  include_tasks: 
    file: snapshot_download.yml
    apply:
      tags: snapshot_download
  tags: 
   - snapshot_download
  when: 
    - selected_mount is defined
    - '"snapshot_download" in ansible_run_tags or ansible_run_tags == ["all"] or "snapshot" in ansible_run_tags'

# Container Deployment Phase
- name: "Phase 3: Deploy Juno container"
  include_tasks: 
    file: container_deployment.yml
    apply:
      tags: deploy_container
  tags:
   - deploy_container
  when:
    - selected_mount is defined
    - '"deploy_container" in ansible_run_tags or ansible_run_tags == ["all"] or "container" in ansible_run_tags'