# starknet-validator-automation/tasks/main.yml
---
# Mount Detection Phase
- name: "Phase 1: Detect and validate storage mounts"
  include_tasks: 
  file: mount_detection.yml
  apply:
    tags: mount
  tags:
   - mount

# Snapshot Download Phase  
- name: "Phase 2: Download and extract Starknet snapshot"
  include_tasks: snapshot_download.yml
  tags: 
   - snapshot_download
  when: 
    - selected_mount is defined
    - '"download" in ansible_run_tags or ansible_run_tags == ["all"] or "snapshot" in ansible_run_tags'

# Container Deployment Phase
- name: "Phase 3: Deploy Juno container"
  include_tasks: container_deployment.yml
  tags:
   - deploy_container
  when:
    - selected_mount is defined
    - '"deploy" in ansible_run_tags or ansible_run_tags == ["all"] or "container" in ansible_run_tags'